version: '3.8'

services:
  nodejs:
    build: .
    ports:
      - '7777:7777'
    depends_on:
      - mongo

  mongo:
    image: mongo
    # env_file: .env
    volumes:
      - 'data-volume:/data/db'
    ports:
      - '27017:27017'

volumes:
  data-volume: