version: '3.8'

services:
  nodejs:
    build: .
    ports:
      - '3000:3000'
    env_file: ./.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports: 
      - '27017:27017'
    env_file: .env

